# Generated by Django 6.0.3 on 2026-03-13 14:51

import django.core.validators
import django.db.models.deletion
import markdownx.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy przepisów',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Narzędzie',
                'verbose_name_plural': 'Narzędzia',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Składnik',
                'verbose_name_plural': 'Składniki',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('preparation_time', models.DurationField(help_text='Format: HH:MM:SS', verbose_name='Czas przygotowania')),
                ('description', markdownx.models.MarkdownxField(max_length=4000, verbose_name='Opis')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.author', verbose_name='Autor przepisu')),
                ('required_equipment', models.ManyToManyField(to='recipes.equipment', verbose_name='Wymagane narzędzia')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
            },
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość')),
                ('unit', models.CharField(choices=[('item', 'szt.'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10, verbose_name='Jednostka')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient', verbose_name='Składnik')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe', verbose_name='Przepis')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_recipe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='no-repeated-ingredient', violation_error_message='Ten składnik został już w innym miejscu dodany do tego przepisu'),
        ),
    ]
