# Generated by Django 6.0.3 on 2026-03-10 18:49

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=markdownx.models.MarkdownxField(max_length=4000),
        ),
    ]
