databases:
  - name: family_db
    plan: free
    databaseName: family_db
    user: admin_user
    region: frankfurt

services:
  - type: web
    plan: free
    name: family_app_backend
    region: frankfurt
    runtime: python
    buildCommand: './build.sh'
    startCommand: "cd family_app && gunicorn family_app.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: family_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"