# Generated by Django 6.0.3 on 2026-03-15 13:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItemsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('item', 'szt.'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10)),
                ('extra_notes', models.CharField(max_length=1000, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.shoppinglist')),
                ('shopping_list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.shoppinglistitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shopping_list', 'shopping_list_item'), name='unique_item')],
            },
        ),
    ]
