# Generated by Django 6.0.3 on 2026-03-15 18:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitemslist_extra_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitemslist',
            options={'verbose_name': 'Przedmiot zakupowy', 'verbose_name_plural': 'Lista przedmiotów zakupowych'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Lista zakupów', 'verbose_name_plural': 'Listy zakupów'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'verbose_name': 'Przemiot zakupowy', 'verbose_name_plural': 'Przedmioty zakupowe'},
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='extra_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dodatkowe uwagi'),
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='shopping_list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping.shoppinglistitem', verbose_name='Przedmiot zakupowy'),
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='unit',
            field=models.CharField(choices=[('item', 'szt.'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Opis/uwagi'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
    ]
