# Generated by Django 6.0.3 on 2026-03-17 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppingitemslist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='shopping.shoppinglist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shopping_list', 'endpoint'), name='unique_list_subscription')],
            },
        ),
    ]
