# Generated by Django 6.0.3 on 2026-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_shoppingitemslist_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nazwa'),
        ),
    ]
