# Generated by Django 6.0.3 on 2026-03-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_shoppinglistitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglist'),
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='shopping_list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglistitem', verbose_name='Przedmiot zakupowy'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tytuł'),
        ),
    ]
