# Generated by Django 6.0.3 on 2026-03-27 20:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_shoppingitemslist_shopping_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='unit',
            field=models.CharField(blank=True, choices=[('item', 'szt.'), ('packet', 'opakowania'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10, null=True, verbose_name='Jednostka'),
        ),
    ]
