# Generated by Django 6.0.3 on 2026-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_alter_shoppingitemslist_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitemslist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
