# Generated by Django 6.0.3 on 2026-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_shoppingitemslist_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa etykiety')),
            ],
            options={
                'verbose_name': 'Etykieta',
                'verbose_name_plural': 'Etykiety',
            },
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='shopping.tag'),
        ),
    ]
