# Generated by Django 6.0.3 on 2026-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_tag_shoppinglistitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='shopping.tag', verbose_name='Etykiety'),
        ),
    ]
