# Generated by Django 6.0.3 on 2026-04-22 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_alter_shoppinglistitem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LackingShoppingListItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość do kupienia')),
                ('unit', models.CharField(blank=True, choices=[('item', 'szt.'), ('packet', 'opakowania'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10, null=True, verbose_name='Jednostka')),
                ('extra_notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Dodatkowe uwagi')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglistitem', verbose_name='Przedmiot zakupowy')),
            ],
        ),
    ]
