# Generated by Django 6.0.3 on 2026-04-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_lackingshoppinglistitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lackingshoppinglistitems',
            options={'verbose_name': 'Brakujący przedmiot zakupowy', 'verbose_name_plural': 'Brakujące przedmioty zakupowe'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'verbose_name': 'Przedmiot zakupowy', 'verbose_name_plural': 'Przedmioty zakupowe'},
        ),
        migrations.AlterField(
            model_name='lackingshoppinglistitems',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Czas ostatniej aktualizacji'),
        ),
        migrations.AlterField(
            model_name='lackingshoppinglistitems',
            name='shopping_list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglistitem', unique=True, verbose_name='Przedmiot zakupowy'),
        ),
    ]
