# Generated by Django 6.0.3 on 2026-04-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_lackingshoppinglistitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lackingshoppinglistitems',
            name='shopping_list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping.shoppinglistitem', verbose_name='Przedmiot zakupowy'),
        ),
    ]
