# Generated by Django 6.0.3 on 2026-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_lackingshoppinglistitems_shopping_list_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='lackingshoppinglistitems',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
