# Generated by Django 6.0.3 on 2026-04-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_lackingshoppinglistitems_is_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lackingshoppinglistitems',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
    ]
