# Generated by Django 6.0.3 on 2026-04-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_rename_last_updated_at_lackingshoppinglistitems_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lackingshoppinglistitems',
            old_name='quantity_to_buy',
            new_name='quantity',
        ),
    ]
