# Generated by Django 6.0.3 on 2026-06-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_rename_quantity_to_buy_lackingshoppinglistitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lackingshoppinglistitems',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ilość do kupienia'),
        ),
    ]
