# Generated by Django 6.0.3 on 2026-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_alter_lackingshoppinglistitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitemslist',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ilość'),
        ),
    ]
