# Generated by Django 6.0.3 on 2026-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitieslog',
            options={'verbose_name': 'Rejestr aktywności', 'verbose_name_plural': 'Rejestr aktywności'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Aktywność', 'verbose_name_plural': 'Aktywności'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Członek rodziny', 'verbose_name_plural': 'Członkowie rodziny'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
