# Generated by Django 6.0.3 on 2026-05-11 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria przedmiotu', 'verbose_name_plural': 'Kategorie przedmiotów'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Przedmiot', 'verbose_name_plural': 'Przedmioty'},
        ),
        migrations.AlterModelOptions(
            name='itemregister',
            options={'verbose_name': 'Rejestr przedmiotu', 'verbose_name_plural': 'Rejestr przedmiotów'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Pokój', 'verbose_name_plural': 'Pokoje'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='itemregister',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość'),
        ),
        migrations.AddField(
            model_name='itemregister',
            name='unit',
            field=models.CharField(blank=True, choices=[('item', 'szt.'), ('packet', 'opakowania'), ('litre', 'l'), ('milliliter', 'ml'), ('kilogram', 'kg'), ('gram', 'g'), ('spoon', 'łyżki'), ('teaspoon', 'łyżeczki'), ('seed', 'ziarna'), ('leaf', 'listki')], max_length=10, null=True, verbose_name='Jednostka'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_register.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='itemregister',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_register.item', verbose_name='Przedmiot'),
        ),
        migrations.AlterField(
            model_name='itemregister',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostatniej aktualizacji'),
        ),
        migrations.AlterField(
            model_name='itemregister',
            name='place_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Opis miejsca'),
        ),
        migrations.AlterField(
            model_name='itemregister',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_register.room', verbose_name='Pokój'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa'),
        ),
    ]
